- name: Install code packages
  command: code --install-extension {{ item }}
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
  with_items:
      - dbaeumer.vscode-eslint
      - eamodio.gitlens
      - EditorConfig.EditorConfig
      - esbenp.prettier-vscode
      - kisstkondoros.vscode-gutter-preview
      - LaurentTreguier.vscode-simple-icons
      - ms-vscode.vscode-typescript-tslint-plugin
      - msjsdiag.debugger-for-chrome
      - wix.vscode-import-cost
      - Orta.vscode-jest
